server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/libmngsys
    username: canberk
    password: bancerk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true
  application:
    name: LibManagerSys
